#!/usr/bin/env bash
#
# install-guardrails.sh — set the local commit identity and install pre-commit /
# pre-push hooks that keep secrets and maintainer-personal material out of git.
#
# This script contains ZERO personal values. The commit identity is read from
# ~/.config/oss-guard/git-identity and the optional personal-identifier denylist
# from ~/.config/oss-guard/deny-patterns.txt. Outside contributors who do not
# have those files still get gitleaks-based secret scanning.
#
# Run once after cloning:  scripts/install-guardrails.sh
#
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$(git rev-parse --git-path hooks)"
IDENTITY_FILE="${OSS_GUARD_IDENTITY:-$HOME/.config/oss-guard/git-identity}"

mkdir -p "$HOOKS_DIR"

# --- 1. Local commit identity ------------------------------------------------
if [ -f "$IDENTITY_FILE" ]; then
  # File format: GIT_USER_NAME=... / GIT_USER_EMAIL=... (one per line).
  GIT_USER_NAME="$(sed -n 's/^GIT_USER_NAME=//p' "$IDENTITY_FILE" | head -n1)"
  GIT_USER_EMAIL="$(sed -n 's/^GIT_USER_EMAIL=//p' "$IDENTITY_FILE" | head -n1)"
  if [ -n "$GIT_USER_NAME" ] && [ -n "$GIT_USER_EMAIL" ]; then
    git -C "$REPO_ROOT" config user.name "$GIT_USER_NAME"
    git -C "$REPO_ROOT" config user.email "$GIT_USER_EMAIL"
    echo "guardrails: set local commit identity to $GIT_USER_NAME <$GIT_USER_EMAIL>"
  else
    echo "guardrails: WARNING $IDENTITY_FILE is malformed; leaving git identity unchanged." >&2
  fi
else
  echo "guardrails: WARNING no identity file at $IDENTITY_FILE; leaving git identity unchanged." >&2
  echo "guardrails: commits must use a GitHub noreply email — see docs/local-development.md." >&2
fi

# --- 2. pre-commit hook ------------------------------------------------------
cat > "$HOOKS_DIR/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-guardrails.sh — do not edit by hand.
set -euo pipefail

DENYLIST="${OSS_GUARD_DENYLIST:-$HOME/.config/oss-guard/deny-patterns.txt}"
fail() { echo "pre-commit BLOCKED: $*" >&2; exit 1; }

# (a) never commit as a denylisted identity (e.g. a personal email).
if [ -f "$DENYLIST" ]; then
  EMAIL="$(git config user.email || true)"
  if [ -n "$EMAIL" ] && printf '%s\n' "$EMAIL" | grep -qiFf <(grep -v '^#' "$DENYLIST" | grep -v '^[[:space:]]*$'); then
    fail "commit identity '$EMAIL' matches a denylisted personal identifier."
  fi
fi

# (b) gitleaks over the staged change.
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks git --pre-commit --staged --no-banner --redact || fail "gitleaks found a secret in the staged change."
else
  echo "pre-commit: WARNING gitleaks not installed; skipping secret scan." >&2
fi

# (c) block force-added ignored paths (private/, overlay files, Makefile.local, ...).
while IFS= read -r -d '' path; do
  if git check-ignore -q "$path"; then
    fail "staged path '$path' is git-ignored (local-only material must never be committed)."
  fi
done < <(git diff --cached --name-only -z --diff-filter=d)

# (d) personal-identifier denylist over staged added lines AND staged paths.
if [ -f "$DENYLIST" ]; then
  PATTERNS="$(mktemp)"; trap 'rm -f "$PATTERNS"' EXIT
  grep -v '^#' "$DENYLIST" | grep -v '^[[:space:]]*$' > "$PATTERNS"
  if [ -s "$PATTERNS" ]; then
    ADDED="$(git diff --cached --no-color -U0 --diff-filter=d | grep -E '^\+' | grep -Ev '^\+\+\+' || true)"
    if [ -n "$ADDED" ] && printf '%s\n' "$ADDED" | grep -qiFf "$PATTERNS"; then
      HIT="$(printf '%s\n' "$ADDED" | grep -ioFf "$PATTERNS" | sort -u | head -n5 | tr '\n' ' ')"
      fail "staged content matches denylisted personal identifier(s): $HIT"
    fi
    PATHS="$(git diff --cached --name-only --diff-filter=d || true)"
    if [ -n "$PATHS" ] && printf '%s\n' "$PATHS" | grep -qiFf "$PATTERNS"; then
      HIT="$(printf '%s\n' "$PATHS" | grep -iFf "$PATTERNS" | head -n5 | tr '\n' ' ')"
      fail "staged path(s) match denylisted personal identifier(s): $HIT"
    fi
  fi
else
  echo "pre-commit: WARNING no denylist at $DENYLIST; running in gitleaks-only mode." >&2
fi

exit 0
HOOK
chmod +x "$HOOKS_DIR/pre-commit"

# --- 3. pre-push hook --------------------------------------------------------
cat > "$HOOKS_DIR/pre-push" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-guardrails.sh — do not edit by hand.
# Covers commits made with --no-verify or by other tools by re-scanning the
# outgoing range for each ref being pushed.
set -euo pipefail

DENYLIST="${OSS_GUARD_DENYLIST:-$HOME/.config/oss-guard/deny-patterns.txt}"
Z40="0000000000000000000000000000000000000000"
fail() { echo "pre-push BLOCKED: $*" >&2; exit 1; }

PATTERNS=""
if [ -f "$DENYLIST" ]; then
  PATTERNS="$(mktemp)"; trap 'rm -f "$PATTERNS"' EXIT
  grep -v '^#' "$DENYLIST" | grep -v '^[[:space:]]*$' > "$PATTERNS"
fi

# stdin: <local ref> <local sha> <remote ref> <remote sha>
while read -r local_ref local_sha remote_ref remote_sha; do
  [ "$local_sha" = "$Z40" ] && continue   # branch deletion
  if [ "$remote_sha" = "$Z40" ]; then
    # new branch on the remote: scan everything it adds over origin/main if known.
    if base="$(git merge-base "$local_sha" origin/main 2>/dev/null)"; then
      range="$base..$local_sha"
    else
      range="$local_sha"                    # no shared base: scan the whole ref
    fi
  else
    range="$remote_sha..$local_sha"
  fi

  if command -v gitleaks >/dev/null 2>&1; then
    if printf '%s' "$range" | grep -q '\.\.'; then
      gitleaks git --no-banner --redact --log-opts="$range" . \
        || fail "gitleaks found a secret in the outgoing range $range."
    else
      gitleaks git --no-banner --redact . \
        || fail "gitleaks found a secret in the outgoing history."
    fi
  fi

  if [ -n "$PATTERNS" ] && [ -s "$PATTERNS" ]; then
    if printf '%s' "$range" | grep -q '\.\.'; then
      ADDED="$(git diff --no-color -U0 "$range" | grep -E '^\+' | grep -Ev '^\+\+\+' || true)"
      if [ -n "$ADDED" ] && printf '%s\n' "$ADDED" | grep -qiFf "$PATTERNS"; then
        HIT="$(printf '%s\n' "$ADDED" | grep -ioFf "$PATTERNS" | sort -u | head -n5 | tr '\n' ' ')"
        fail "outgoing range $range contains denylisted personal identifier(s): $HIT"
      fi
    fi
  fi
done

exit 0
HOOK
chmod +x "$HOOKS_DIR/pre-push"

echo "guardrails: installed pre-commit and pre-push hooks in $HOOKS_DIR"
